"""Deterministic firmware source generation for the firmware skills (FORGE-545).

The three firmware skills used to return file *paths* with no content, pin
names they made up (``STM32F4_DEFAULT``) and one hard-coded register map for
every part. Everything generated here comes from the caller's inputs: the
board's real pin map, the part's register list from its datasheet, the
tasks' real stack sizes and priorities. A required figure that is missing
is refused, never defaulted.
"""

from __future__ import annotations

import re
from typing import Any

from pydantic import BaseModel, Field


class GeneratedFile(BaseModel):
    """One generated source file, path and full text."""

    path: str
    content: str


class CodegenError(ValueError):
    """Inputs that cannot produce correct source."""


_IDENT = re.compile(r"[^A-Za-z0-9]+")


def c_ident(name: str) -> str:
    """``imu cs-1`` -> ``IMU_CS_1``; refuses a name with nothing usable in it."""
    ident = _IDENT.sub("_", name).strip("_").upper()
    if not ident:
        raise CodegenError(f"{name!r} has no characters usable in a C identifier")
    return f"_{ident}" if ident[0].isdigit() else ident


def _banner(what: str, source: str) -> str:
    lines = [
        "/*",
        f" * {what}",
        " * Generated by MetaForge from the inputs below; regenerate rather than edit.",
    ]
    if source:
        lines.append(f" * Source: {source}")
    lines.append(" */")
    return "\n".join(lines) + "\n"


def _guard(path: str) -> str:
    return c_ident(path.rsplit("/", 1)[-1]) + "_"


# ---------------------------------------------------------------------------
# HAL pin definitions
# ---------------------------------------------------------------------------

_STM32 = re.compile(r"^P([A-K])(\d{1,2})$", re.IGNORECASE)
_SAMD = re.compile(r"^P([A-D])(\d{1,2})$", re.IGNORECASE)
_ESP_RP = re.compile(r"^(?:GPIO|GP|IO)?(\d{1,2})$", re.IGNORECASE)
_NRF = re.compile(r"^P(\d)\.(\d{1,2})$", re.IGNORECASE)


def pin_macros(family: str, pin: str) -> list[tuple[str, str]]:
    """Vendor macros for ``pin`` on ``family``: ``[(suffix, value), ...]``."""
    p = pin.strip()
    if family in {"STM32F4", "STM32H7"}:
        m = _STM32.match(p)
        if m and int(m.group(2)) <= 15:
            return [("PORT", f"GPIO{m.group(1).upper()}"), ("PIN", f"GPIO_PIN_{int(m.group(2))}")]
    elif family == "ATSAMD":
        m = _SAMD.match(p)
        if m and int(m.group(2)) <= 31:
            return [("PIN", f"PIN_P{m.group(1).upper()}{int(m.group(2)):02d}")]
    elif family == "ESP32":
        m = _ESP_RP.match(p)
        if m and int(m.group(1)) <= 48:
            return [("PIN", f"GPIO_NUM_{int(m.group(1))}")]
    elif family == "RP2040":
        m = _ESP_RP.match(p)
        if m and int(m.group(1)) <= 29:
            return [("PIN", str(int(m.group(1))))]
    elif family == "nRF52":
        m = _NRF.match(p)
        if m and int(m.group(1)) <= 1 and int(m.group(2)) <= 31:
            return [("PIN", f"NRF_GPIO_PIN_MAP({m.group(1)}, {int(m.group(2))})")]
    raise CodegenError(f"pin {pin!r} is not a valid {family} pin name")


def generate_hal_files(
    family: str, pin_map: list[dict[str, Any]], output_dir: str, source: str
) -> tuple[list[GeneratedFile], dict[str, str]]:
    """``board_pins.h`` (and ``board_peripherals.h``) from a real pin map."""
    by_pin: dict[str, str] = {}
    lines: list[str] = []
    peripherals: dict[str, list[str]] = {}
    mapping: dict[str, str] = {}
    for row in pin_map:
        signal, pin = str(row.get("signal", "")).strip(), str(row.get("pin", "")).strip()
        if not signal or not pin:
            raise CodegenError(f"pin_map row needs signal and pin: {row}")
        ident = c_ident(signal)
        key = pin.upper()
        if key in by_pin:
            raise CodegenError(f"pin {pin} is assigned to both {by_pin[key]} and {signal}")
        by_pin[key] = signal
        if ident in mapping:
            raise CodegenError(f"signal {signal} appears twice")
        mapping[ident] = pin
        note = " ".join(str(row[k]) for k in ("peripheral", "function", "direction") if row.get(k))
        lines.append(f"/* {signal}: {pin}{(' ' + note) if note else ''} */")
        for suffix, value in pin_macros(family, pin):
            lines.append(f"#define BOARD_{ident}_{suffix} {value}")
        if row.get("peripheral"):
            peripherals.setdefault(c_ident(str(row["peripheral"])), []).append(ident)

    pins_path = f"{output_dir}/board_pins.h"
    guard = _guard(pins_path)
    pins = (
        _banner(f"Board pin definitions for {family}", source)
        + f"#ifndef {guard}\n#define {guard}\n\n"
        + "\n".join(lines)
        + f"\n\n#endif /* {guard} */\n"
    )
    files = [GeneratedFile(path=pins_path, content=pins)]
    if peripherals:
        per_path = f"{output_dir}/board_peripherals.h"
        guard = _guard(per_path)
        body = []
        for periph, signals in sorted(peripherals.items()):
            body.append(f"#define BOARD_USES_{periph} 1 /* {', '.join(signals)} */")
        files.append(
            GeneratedFile(
                path=per_path,
                content=_banner(f"Peripheral instances used on this {family} board", source)
                + f"#ifndef {guard}\n#define {guard}\n\n"
                + "\n".join(body)
                + f"\n\n#endif /* {guard} */\n",
            )
        )
    return files, mapping


# ---------------------------------------------------------------------------
# Register-level driver
# ---------------------------------------------------------------------------

_ACCESS = {"r": "read-only", "w": "write-only", "rw": "read-write"}


def generate_driver_files(
    driver_name: str,
    interface: str,
    registers: list[dict[str, Any]],
    address_bits: int,
    base_dir: str,
    source: str,
) -> tuple[list[GeneratedFile], dict[str, Any]]:
    """``<name>_regs.h``, ``<name>.h`` and ``<name>.c`` from a datasheet register list.

    The driver is portable: register reads and writes go through bus
    callbacks the board supplies, so nothing here is vendor-specific.
    """
    name = c_ident(driver_name).lower()
    upper = name.upper()
    limit = (1 << address_bits) - 1
    seen_names: set[str] = set()
    seen_addr: dict[int, str] = {}
    reg_lines: list[str] = []
    register_map: dict[str, Any] = {}
    check: tuple[str, int] | None = None
    for reg in registers:
        rname = c_ident(str(reg.get("name", "")))
        address = _int(reg.get("address"), f"register {rname} address")
        if not 0 <= address <= limit:
            raise CodegenError(
                f"register {rname} address {address:#x} does not fit {address_bits} bits"
            )
        access = str(reg.get("access", "")).lower()
        if access not in _ACCESS:
            raise CodegenError(f"register {rname} access must be r, w or rw, not {access!r}")
        if rname in seen_names:
            raise CodegenError(f"register {rname} appears twice")
        if address in seen_addr:
            raise CodegenError(
                f"registers {seen_addr[address]} and {rname} share address {address:#x}"
            )
        seen_names.add(rname)
        seen_addr[address] = rname
        width = (address_bits + 3) // 4
        desc = str(reg.get("description", "")).strip()
        reg_lines.append(
            f"#define {upper}_REG_{rname} 0x{address:0{width}X}u /* {_ACCESS[access]}"
            f"{'; ' + desc if desc else ''} */"
        )
        entry: dict[str, Any] = {"address": f"0x{address:0{width}X}", "access": _ACCESS[access]}
        if reg.get("reset") is not None:
            reset = _int(reg["reset"], f"register {rname} reset")
            reg_lines.append(f"#define {upper}_REG_{rname}_RESET 0x{reset:02X}u")
            entry["reset"] = f"0x{reset:02X}"
        if reg.get("expected") is not None:
            if access == "w":
                raise CodegenError(f"register {rname} is write-only and cannot hold an id")
            expected = _int(reg["expected"], f"register {rname} expected")
            reg_lines.append(f"#define {upper}_{rname}_EXPECTED 0x{expected:02X}u")
            entry["expected"] = f"0x{expected:02X}"
            if check is None:
                check = (rname, expected)
        register_map[rname] = entry

    addr_t = "uint8_t" if address_bits <= 8 else "uint16_t"
    regs_path = f"{base_dir}/{name}_regs.h"
    head_path = f"{base_dir}/{name}.h"
    src_path = f"{base_dir}/{name}.c"
    g1, g2 = _guard(regs_path), _guard(head_path)
    regs_h = (
        _banner(f"{driver_name} register map ({interface})", source)
        + f"#ifndef {g1}\n#define {g1}\n\n"
        + "\n".join(reg_lines)
        + f"\n\n#endif /* {g1} */\n"
    )
    head_h = (
        _banner(f"{driver_name} driver over {interface}", source)
        + f"#ifndef {g2}\n#define {g2}\n\n#include <stddef.h>\n#include <stdint.h>\n\n"
        + f'#include "{name}_regs.h"\n\n'
        + "/* Bus access supplied by the board: return 0 on success. */\n"
        + f"typedef int (*{name}_read_fn)(void *bus, {addr_t} reg, uint8_t *data, size_t len);\n"
        + f"typedef int (*{name}_write_fn)(void *bus, {addr_t} reg, const uint8_t *data, "
        + "size_t len);\n\n"
        + f"typedef struct {{\n    void *bus;\n    {name}_read_fn read;\n"
        + f"    {name}_write_fn write;\n}} {name}_t;\n\n"
        + f"int {name}_read_reg(const {name}_t *dev, {addr_t} reg, uint8_t *value);\n"
        + f"int {name}_write_reg(const {name}_t *dev, {addr_t} reg, uint8_t value);\n"
        + f"int {name}_init(const {name}_t *dev);\n\n#endif /* {g2} */\n"
    )
    if check is not None:
        init_body = (
            "    uint8_t id = 0;\n"
            f"    int rc = {name}_read_reg(dev, {upper}_REG_{check[0]}, &id);\n"
            f"    if (rc != 0) {{\n        return rc;\n    }}\n"
            f"    return id == {upper}_{check[0]}_EXPECTED ? 0 : -2; /* -2: wrong part */\n"
        )
    else:
        init_body = (
            "    /* No register with an expected value was given, so there is no\n"
            "     * identity check; configuration writes belong here. */\n"
            "    return dev != NULL && dev->read != NULL && dev->write != NULL ? 0 : -1;\n"
        )
    src_c = (
        _banner(f"{driver_name} driver over {interface}", source)
        + f'#include "{name}.h"\n\n'
        + f"int {name}_read_reg(const {name}_t *dev, {addr_t} reg, uint8_t *value)\n{{\n"
        + "    if (dev == NULL || dev->read == NULL || value == NULL) {\n        return -1;\n"
        + "    }\n    return dev->read(dev->bus, reg, value, 1);\n}\n\n"
        + f"int {name}_write_reg(const {name}_t *dev, {addr_t} reg, uint8_t value)\n{{\n"
        + "    if (dev == NULL || dev->write == NULL) {\n        return -1;\n    }\n"
        + "    return dev->write(dev->bus, reg, &value, 1);\n}\n\n"
        + f"int {name}_init(const {name}_t *dev)\n{{\n"
        + init_body
        + "}\n"
    )
    files = [
        GeneratedFile(path=regs_path, content=regs_h),
        GeneratedFile(path=head_path, content=head_h),
        GeneratedFile(path=src_path, content=src_c),
    ]
    return files, register_map


def _int(value: Any, what: str) -> int:
    if isinstance(value, bool):
        raise CodegenError(f"{what} must be an integer")
    if isinstance(value, int):
        return value
    try:
        return int(str(value).strip(), 0)
    except ValueError as exc:
        raise CodegenError(f"{what} {value!r} is not an integer") from exc


# ---------------------------------------------------------------------------
# RTOS configuration
# ---------------------------------------------------------------------------

#: RTOSes with a real generator. Others are refused rather than given a path.
GENERATED_RTOS = ("FreeRTOS", "Zephyr")


class RtosTask(BaseModel):
    name: str = Field(..., min_length=1)
    priority: int = Field(..., ge=0)
    stack_size: int = Field(..., gt=0, description="Stack size in bytes")
    entry: str | None = Field(default=None, description="Entry function; defaults to <name>_task")


def generate_rtos_files(
    rtos: str,
    tasks: list[RtosTask],
    heap_size_kb: int,
    tick_rate_hz: int,
    output_dir: str,
    stack_word_bytes: int,
) -> tuple[list[GeneratedFile], int]:
    """Config and task table for ``rtos``; returns the files and RAM estimate (bytes)."""
    if rtos not in GENERATED_RTOS:
        raise CodegenError(f"no generator for {rtos}; generated: {', '.join(GENERATED_RTOS)}")
    idents = [c_ident(t.name).lower() for t in tasks]
    if len(set(idents)) != len(idents):
        raise CodegenError("task names must be unique")
    for t in tasks:
        if t.stack_size % stack_word_bytes:
            raise CodegenError(
                f"task {t.name} stack_size {t.stack_size} is not a multiple of the "
                f"{stack_word_bytes}-byte stack word"
            )
    heap_bytes = heap_size_kb * 1024
    ram = heap_bytes + sum(t.stack_size for t in tasks)
    entries = [t.entry or f"{i}_task" for t, i in zip(tasks, idents, strict=True)]

    if rtos == "FreeRTOS":
        max_prio = max(t.priority for t in tasks) + 1
        min_stack_words = min(t.stack_size for t in tasks) // stack_word_bytes
        cfg_path = f"{output_dir}/FreeRTOSConfig.h"
        g = _guard(cfg_path)
        cfg = (
            _banner("FreeRTOS kernel configuration", "")
            + f"#ifndef {g}\n#define {g}\n\n"
            + "#define configUSE_PREEMPTION 1\n"
            + f"#define configTICK_RATE_HZ ((TickType_t){tick_rate_hz})\n"
            + f"#define configMAX_PRIORITIES {max_prio}\n"
            + f"#define configMINIMAL_STACK_SIZE ((uint16_t){min_stack_words})\n"
            + f"#define configTOTAL_HEAP_SIZE ((size_t){heap_bytes})\n"
            + "#define configSUPPORT_DYNAMIC_ALLOCATION 1\n"
            + "#define configUSE_MUTEXES 1\n"
            + "#define configCHECK_FOR_STACK_OVERFLOW 2\n"
            + f"\n#endif /* {g} */\n"
        )
        rows = [
            f'    {{ {e}, "{t.name}", {t.stack_size // stack_word_bytes}u, {t.priority}u }},'
            f" /* {t.stack_size} bytes */"
            for t, e in zip(tasks, entries, strict=True)
        ]
        decls = "\n".join(f"void {e}(void *arg);" for e in entries)
        tasks_path = f"{output_dir}/app_tasks.c"
        task_c = (
            _banner("Application task table (FreeRTOS)", "")
            + '#include "FreeRTOS.h"\n#include "task.h"\n\n'
            + decls
            + "\n\nstatic const struct {\n    TaskFunction_t entry;\n    const char *name;\n"
            + "    configSTACK_DEPTH_TYPE depth_words;\n    UBaseType_t priority;\n"
            + "} app_tasks[] = {\n"
            + "\n".join(rows)
            + "\n};\n\nint app_tasks_create(void)\n{\n"
            + "    for (size_t i = 0; i < sizeof app_tasks / sizeof app_tasks[0]; i++) {\n"
            + "        if (xTaskCreate(app_tasks[i].entry, app_tasks[i].name,\n"
            + "                        app_tasks[i].depth_words, NULL,\n"
            + "                        app_tasks[i].priority, NULL) != pdPASS) {\n"
            + "            return -1;\n        }\n    }\n    return 0;\n}\n"
        )
        return [
            GeneratedFile(path=cfg_path, content=cfg),
            GeneratedFile(path=tasks_path, content=task_c),
        ], ram

    # Zephyr: lower number is higher priority for preemptible threads, which
    # is the reverse of the convention the inputs use (higher = more urgent).
    top = max(t.priority for t in tasks)
    conf_path = f"{output_dir}/prj.conf"
    conf = (
        "# Zephyr kernel configuration, generated by MetaForge; regenerate rather than edit.\n"
        f"CONFIG_SYS_CLOCK_TICKS_PER_SEC={tick_rate_hz}\n"
        f"CONFIG_HEAP_MEM_POOL_SIZE={heap_bytes}\n"
        f"CONFIG_NUM_PREEMPT_PRIORITIES={top + 1}\n"
    )
    rows = [
        f"K_THREAD_DEFINE({i}_tid, {t.stack_size}, {e}, NULL, NULL, NULL, "
        f"{top - t.priority}, 0, 0);"
        for t, i, e in zip(tasks, idents, entries, strict=True)
    ]
    decls = "\n".join(f"void {e}(void *a, void *b, void *c);" for e in entries)
    threads_path = f"{output_dir}/app_threads.c"
    threads = (
        _banner("Application threads (Zephyr); priority inverted to Zephyr's order", "")
        + "#include <zephyr/kernel.h>\n\n"
        + decls
        + "\n\n"
        + "\n".join(rows)
        + "\n"
    )
    return [
        GeneratedFile(path=conf_path, content=conf),
        GeneratedFile(path=threads_path, content=threads),
    ], ram
