import type { CurrentView, ItemDiff, ItemHistory } from '../../../api/endpoints/items';

export const CURRENT_VIEW: CurrentView = {
  project_id: 'proj-001',
  items: [
    {
      key: 'CAD-BRACKET',
      item_type: 'cad_model',
      name: 'Bracket',
      revision: 3,
      ref: 'CAD-BRACKET@3',
      node_id: 'n-b3',
      revision_status: 'approved',
      validation_status: 'valid',
      run_id: 'run-abcdef123456',
      gate_id: 'G6',
      change_reason: 'thicker wall',
      author: 'agent',
      updated_at: new Date().toISOString(),
      revision_count: 3,
      evidence_state: 'out_of_date',
      evidence_count: 1,
      drafts: [
        {
          revision: 4,
          node_id: 'n-b4',
          status: 'draft',
          name: 'Bracket',
          run_id: 'run-999999999999',
          change_reason: null,
          created_at: null,
        },
      ],
    },
    {
      key: 'CS-PAYLOAD',
      item_type: 'constraint_set',
      name: 'Payload',
      revision: 1,
      ref: 'CS-PAYLOAD@1',
      node_id: 'n-cs1',
      revision_status: 'committed',
      validation_status: 'unknown',
      run_id: null,
      gate_id: null,
      change_reason: null,
      author: null,
      updated_at: null,
      revision_count: 1,
      evidence_state: 'none',
      evidence_count: 0,
      drafts: [],
    },
    {
      key: 'CAD-NEWPART',
      item_type: 'cad_model',
      name: 'New part',
      revision: null,
      ref: null,
      node_id: null,
      revision_status: 'draft',
      validation_status: 'unknown',
      run_id: null,
      gate_id: null,
      change_reason: null,
      author: null,
      updated_at: null,
      revision_count: 1,
      evidence_state: 'none',
      evidence_count: 0,
      drafts: [
        {
          revision: 1,
          node_id: 'n-new1',
          status: 'draft',
          name: 'New part',
          run_id: 'run-999999999999',
          change_reason: null,
          created_at: null,
        },
      ],
    },
  ],
  groups: [
    { item_type: 'cad_model', count: 1, keys: ['CAD-BRACKET'] },
    { item_type: 'constraint_set', count: 1, keys: ['CS-PAYLOAD'] },
  ],
  records: [
    { node_id: 'r-dec', record_type: 'design_decision', name: 'Use 6061', created_at: null, analysed: [], out_of_date: false },
    {
      node_id: 'r-fea1',
      record_type: 'simulation_result',
      name: 'FEA v1',
      created_at: null,
      analysed: [{ key: 'CAD-BRACKET', revision: 1, ref: 'CAD-BRACKET@1', current: false }],
      out_of_date: true,
    },
  ],
  other: [{ node_id: 'o-pin', name: 'Pinmap', type: 'pinmap', validation_status: 'valid', updated_at: null }],
  counts: {
    items: 2,
    other: 1,
    total: 3,
    valid: 2,
    warning: 0,
    error: 0,
    unknown: 1,
    drafts: 2,
    superseded_revisions: 2,
    decisions: 1,
    simulation_results: 1,
    evidence: 0,
    out_of_date_results: 1,
    by_type: { cad_model: 1, constraint_set: 1 },
  },
  readiness: 67,
  latest_baseline: null,
};

export const HISTORY: ItemHistory = {
  item: {
    key: 'CAD-BRACKET',
    item_type: 'cad_model',
    name: 'Bracket',
    project_id: 'proj-001',
    head_revision: 3,
    head_node_id: 'n-b3',
    head_ref: 'CAD-BRACKET@3',
  },
  revisions: [1, 2, 3].map((n) => ({
    revision: n,
    node_id: `n-b${n}`,
    name: 'Bracket',
    change_reason: n === 3 ? "Approved at gate 'G6' by alice" : null,
    run_id: n === 3 ? 'run-abcdef123456' : null,
    author: 'agent',
    created_at: new Date().toISOString(),
    is_head: n === 3,
    adopted: false,
    status: n === 3 ? 'approved' : 'committed',
    change_set: null,
    phase: null,
    gate: n === 3 ? 'G6' : null,
    status_reason: null,
    baselines: n === 3 ? ['bl-1'] : [],
  })),
  current: { revision: 3, node_id: 'n-b3', ref: 'CAD-BRACKET@3' },
};

export const DIFF: ItemDiff = {
  key: 'CAD-BRACKET',
  item_type: 'cad_model',
  name: 'Bracket',
  a: { revision: 2, node_id: 'n-b2', status: 'committed', name: 'Bracket' },
  b: { revision: 3, node_id: 'n-b3', status: 'approved', name: 'Bracket' },
  a_ref: 'CAD-BRACKET@2',
  b_ref: 'CAD-BRACKET@3',
  geometry: {
    available: true,
    source: 'recorded',
    a: { volume_mm3: 1000, bounding_box: { x: 10, z: 5 }, mass_kg: 0.0027 },
    b: { volume_mm3: 1500, bounding_box: { x: 10, z: 6 }, mass_kg: 0.00405 },
    volume_delta_mm3: 500,
    mass_delta_kg: 0.00135,
    mass_source: 'volume x aluminum_6061 density',
    bounding_box_delta: { z: 1 },
  },
  parameters: [{ name: 'thickness_mm', status: 'changed', from: 3, to: 4 }],
  requirements: [
    { name: 'payload', status: 'changed', from: '>= 1 kg', to: '>= 2 kg', from_severity: 'error', to_severity: 'error', unit: 'kg' },
  ],
  fields: [],
  dependents: [{ node_id: 'r-fea1', name: 'FEA v2', type: 'simulation_result', via: 'metadata' }],
  warnings: [],
};
