import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Play, RefreshCw, Search } from 'lucide-react';
import { StatusBadge } from '../components/shared/StatusBadge';
import { useRuns } from '../hooks/use-runs';
export function RunsPage() {
  const query = useRuns();
  const [filter,setFilter] = useState('');
  const [status,setStatus] = useState('all');
  const items = (query.data??[]).filter(run=>(status==='all'||run.status===status)&&`${run.id} ${String(run.request.goal??'')}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt);
  return <div><div className="page-heading"><div><p className="eyebrow">EXECUTION & EVIDENCE</p><h1>Runs<span className="heading-period">.</span></h1><p className="page-description">Follow execution, inspect outcomes, and review approval gates.</p></div><button className="action-secondary" onClick={()=>void query.refetch()} disabled={query.isFetching}><RefreshCw size={16}/>Refresh</button></div><div className="project-toolbar"><label className="project-search"><Search size={18}/><input aria-label="Search runs" placeholder="Search by goal or run ID…" value={filter} onChange={e=>setFilter(e.target.value)}/></label><select aria-label="Run status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['running','queued','awaiting_approval','completed','failed','rejected','canceled'].map(s=><option key={s} value={s}>{s.replace(/_/g,' ')}</option>)}</select></div>{query.isLoading?<div className="workspace-empty" role="status">Loading runs…</div>:query.isError?<div className="workspace-empty" role="alert"><h2>Runs could not be loaded</h2><p>Check your gateway connection and try again.</p><Link className="text-action" to="/settings">Connection settings<ArrowUpRight size={16}/></Link></div>:!items.length?<div className="workspace-empty"><Play size={34}/><h2>{filter||status!=='all'?'No matching runs':'No runs yet'}</h2><p>{filter||status!=='all'?'Try another search or status.':'Runs started through your MetaForge CLI or MCP client appear here, with their execution history and review gates.'}</p></div>:<div className="runs-table-wrap"><table className="runs-table"><thead><tr><th scope="col">Goal / Run</th><th scope="col">Status</th><th scope="col">Last updated</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{items.map(run=><tr key={run.id}><td><Link to={`/runs/${run.id}`}><strong>{String(run.request.goal??'Untitled run')}</strong><small>{run.id}</small></Link></td><td><StatusBadge status={run.status} dot/></td><td><time dateTime={new Date(run.updatedAt*1000).toISOString()}>{new Date(run.updatedAt*1000).toLocaleString()}</time></td><td><Link className="text-action" to={`/runs/${run.id}`}>Inspect<ArrowUpRight size={15}/></Link></td></tr>)}</tbody></table></div>}</div>;
}
