"""Design IR — the versioned parametric-design schema (requirements doc §6)."""

from twin_core.design_ir.models import (
    BooleanEntity,
    ChamferEdgesEntity,
    ChamferEntity,
    CreateAssemblyEntity,
    CreateBodyEntity,
    CreateParametricEntity,
    CreatePrimitiveEntity,
    DesignIR,
    FilletEdgesEntity,
    FilletEntity,
    IREntity,
    IREntityBase,
    JointEntity,
    LinearPatternEntity,
    LoftEntity,
    MirrorEntity,
    PadEntity,
    PlaceEntity,
    PocketEntity,
    PolarPatternEntity,
    RevolveEntity,
    ShellEntity,
    SketchArc,
    SketchCircle,
    SketchElement,
    SketchEntity,
    SketchLine,
    SketchRectangle,
    SweepEntity,
    TransformEntity,
)
from twin_core.design_ir.tiers import OP_TIER, Tier, tier_for
from twin_core.design_ir.validation import validate_design_ir, validate_referential_integrity

__all__ = [
    # Container
    "DesignIR",
    "IREntity",
    "IREntityBase",
    # Sketch elements
    "SketchElement",
    "SketchLine",
    "SketchCircle",
    "SketchRectangle",
    "SketchArc",
    # Entities
    "CreatePrimitiveEntity",
    "CreateParametricEntity",
    "CreateBodyEntity",
    "SketchEntity",
    "PadEntity",
    "PocketEntity",
    "RevolveEntity",
    "LoftEntity",
    "SweepEntity",
    "FilletEdgesEntity",
    "ChamferEdgesEntity",
    "LinearPatternEntity",
    "PolarPatternEntity",
    "MirrorEntity",
    "ShellEntity",
    "BooleanEntity",
    "FilletEntity",
    "ChamferEntity",
    "TransformEntity",
    "CreateAssemblyEntity",
    "PlaceEntity",
    "JointEntity",
    # Tiers
    "Tier",
    "OP_TIER",
    "tier_for",
    # Validation
    "validate_design_ir",
    "validate_referential_integrity",
]
