"""MCP core -- Model Context Protocol client layer for MetaForge."""

from mcp_core.client import InMemoryTransport, McpClient, Transport
from mcp_core.context import (
    McpCallContext,
    context_from_env,
    context_from_headers,
    current_context,
    reset_context,
    set_context,
    with_context,
)
from mcp_core.errors import (
    RETRYABLE_CODES,
    ErrorCode,
    McpToolError,
    make_tool_error,
)
from mcp_core.progress import (
    ProgressEmitter,
    current_emitter,
    emit_progress,
    progress_notification,
    reset_emitter,
    set_emitter,
)
from mcp_core.protocol import (
    McpError,
    ToolExecutionError,
    ToolTimeoutError,
    ToolUnavailableError,
)
from mcp_core.resources import (
    SCHEME,
    ParsedResourceUri,
    ResourceUriError,
    parse_resource_uri,
)
from mcp_core.schemas import (
    HealthStatus,
    JsonRpcErrorResponse,
    JsonRpcRequest,
    JsonRpcSuccessResponse,
    ResourceContent,
    ResourceListRequest,
    ResourceListResult,
    ResourceManifest,
    ResourceReadRequest,
    ResourceReadResult,
    ToolCallRequest,
    ToolCallResult,
    ToolManifest,
    ToolProgress,
)
from mcp_core.transports import LoopbackTransport
from mcp_core.versioning import (
    DEFAULT_VERSION,
    deprecation_message,
    normalise_version,
    parse_versioned_tool_id,
    versioned_tool_id,
)

__all__ = [
    "DEFAULT_VERSION",
    "RETRYABLE_CODES",
    "SCHEME",
    "ErrorCode",
    "HealthStatus",
    "InMemoryTransport",
    "JsonRpcErrorResponse",
    "JsonRpcRequest",
    "JsonRpcSuccessResponse",
    "LoopbackTransport",
    "McpCallContext",
    "McpClient",
    "McpError",
    "McpToolError",
    "ParsedResourceUri",
    "ProgressEmitter",
    "ResourceContent",
    "ResourceListRequest",
    "ResourceListResult",
    "ResourceManifest",
    "ResourceReadRequest",
    "ResourceReadResult",
    "ResourceUriError",
    "ToolCallRequest",
    "ToolCallResult",
    "ToolExecutionError",
    "ToolManifest",
    "ToolProgress",
    "ToolTimeoutError",
    "ToolUnavailableError",
    "Transport",
    "context_from_env",
    "context_from_headers",
    "current_context",
    "current_emitter",
    "deprecation_message",
    "emit_progress",
    "make_tool_error",
    "normalise_version",
    "parse_resource_uri",
    "parse_versioned_tool_id",
    "progress_notification",
    "reset_context",
    "reset_emitter",
    "set_context",
    "set_emitter",
    "versioned_tool_id",
    "with_context",
]
