"""Unit tests for the CalculiX ``.inp`` mesh parser.

The parser has to survive what real meshers emit: multi-line connectivity
records, ``GENERATE`` set ranges, sets that reference other sets, and decks that
already carry physics. Counting lines instead of parsing records is what made
the previous mesh validator report wrong element counts for anything with a
quadratic element in it.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tool_registry.tools.calculix.mesh import (
    Element,
    Mesh,
    MeshParseError,
    parse_inp_mesh,
    select_nodes_on_face,
)

SIMPLE_MESH = """\
** Generated by FreeCAD
*NODE, NSET=Nall
1, 0.0, 0.0, 0.0
2, 10.0, 0.0, 0.0
3, 0.0, 10.0, 0.0
4, 0.0, 0.0, 10.0
5, 10.0, 10.0, 10.0
*ELEMENT, TYPE=C3D4, ELSET=Volume1
1, 1, 2, 3, 4
2, 2, 3, 4, 5
"""

# A C3D10 record does not fit on one line; the continuation comma is what tells
# the parser the record continues.
QUADRATIC_MESH = """\
*NODE
1, 0.0, 0.0, 0.0
2, 1.0, 0.0, 0.0
3, 0.0, 1.0, 0.0
4, 0.0, 0.0, 1.0
5, 0.5, 0.0, 0.0
6, 0.5, 0.5, 0.0
7, 0.0, 0.5, 0.0
8, 0.0, 0.0, 0.5
9, 0.5, 0.0, 0.5
10, 0.0, 0.5, 0.5
*ELEMENT, TYPE=C3D10, ELSET=Volume1
1, 1, 2, 3, 4, 5, 6, 7,
8, 9, 10
"""


def write(tmp_path: Path, content: str, name: str = "mesh.inp") -> Path:
    path = tmp_path / name
    path.write_text(content, encoding="utf-8")
    return path


class TestParsing:
    def test_parses_nodes_and_elements(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.node_count == 5
        assert mesh.element_count == 2
        assert mesh.element_types == ["C3D4"]

    def test_node_coordinates_are_floats(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.nodes[2] == (10.0, 0.0, 0.0)

    def test_multi_line_connectivity_is_one_element(self, tmp_path: Path) -> None:
        """A C3D10 spans two physical lines but is a single element."""
        mesh = parse_inp_mesh(write(tmp_path, QUADRATIC_MESH))
        assert mesh.element_count == 1
        assert len(mesh.elements[1].nodes) == 10

    def test_comments_and_blank_lines_are_ignored(self, tmp_path: Path) -> None:
        content = "** header comment\n\n" + SIMPLE_MESH + "\n** trailing\n"
        mesh = parse_inp_mesh(write(tmp_path, content))
        assert mesh.node_count == 5

    def test_unknown_keywords_are_skipped(self, tmp_path: Path) -> None:
        """A deck that has already been solved must still parse as a mesh."""
        content = SIMPLE_MESH + "*MATERIAL, NAME=STEEL\n*ELASTIC\n210000, 0.3\n*STEP\n*STATIC\n"
        mesh = parse_inp_mesh(write(tmp_path, content))
        assert mesh.node_count == 5
        assert mesh.element_count == 2

    def test_malformed_records_are_skipped_not_fatal(self, tmp_path: Path) -> None:
        content = SIMPLE_MESH.replace("3, 0.0, 10.0, 0.0", "3, not_a_number, 10.0, 0.0")
        mesh = parse_inp_mesh(write(tmp_path, content))
        assert mesh.node_count == 4

    def test_missing_file_raises(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError):
            parse_inp_mesh(tmp_path / "absent.inp")

    def test_mesh_with_no_nodes_raises(self, tmp_path: Path) -> None:
        with pytest.raises(MeshParseError, match="No nodes"):
            parse_inp_mesh(write(tmp_path, "*ELEMENT, TYPE=C3D4\n1, 1, 2, 3, 4\n"))

    def test_mesh_with_no_elements_raises(self, tmp_path: Path) -> None:
        with pytest.raises(MeshParseError, match="No elements"):
            parse_inp_mesh(write(tmp_path, "*NODE\n1, 0.0, 0.0, 0.0\n"))


class TestSets:
    def test_nset_on_node_keyword_is_captured(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.node_sets["Nall"] == [1, 2, 3, 4, 5]

    def test_elset_on_element_keyword_is_captured(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.element_sets["Volume1"] == [1, 2]

    def test_generate_expands_a_range(self, tmp_path: Path) -> None:
        content = SIMPLE_MESH + "*NSET, NSET=Base, GENERATE\n1, 5, 2\n"
        mesh = parse_inp_mesh(write(tmp_path, content))
        assert mesh.node_sets["Base"] == [1, 3, 5]

    def test_set_can_reference_another_set(self, tmp_path: Path) -> None:
        content = SIMPLE_MESH + "*ELSET, ELSET=Eall\nVolume1\n"
        mesh = parse_inp_mesh(write(tmp_path, content))
        assert mesh.element_sets["Eall"] == [1, 2]

    def test_set_lookup_is_case_insensitive(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.resolve_node_set("nALL") == [1, 2, 3, 4, 5]

    def test_unknown_set_raises_key_error(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        with pytest.raises(KeyError):
            mesh.resolve_node_set("nope")


class TestGeometry:
    def test_bounding_box(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.bounding_box() == ((0.0, 0.0, 0.0), (10.0, 10.0, 10.0))

    def test_characteristic_length_is_the_diagonal(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert mesh.characteristic_length() == pytest.approx(10.0 * 3**0.5)

    def test_bounding_box_of_empty_mesh_raises(self) -> None:
        with pytest.raises(MeshParseError):
            Mesh().bounding_box()

    @pytest.mark.parametrize(
        ("face", "expected"),
        [
            ("zmin", [1, 2, 3]),
            ("xmin", [1, 3, 4]),
            ("xmax", [2, 5]),
            ("ymax", [3, 5]),
        ],
    )
    def test_face_selection(self, tmp_path: Path, face: str, expected: list[int]) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert select_nodes_on_face(mesh, face) == expected

    def test_face_name_is_case_and_separator_insensitive(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert select_nodes_on_face(mesh, "Z_MIN") == select_nodes_on_face(mesh, "zmin")

    def test_unknown_face_raises(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        with pytest.raises(ValueError, match="Unknown face"):
            select_nodes_on_face(mesh, "topside")

    def test_explicit_tolerance_widens_the_selection(self, tmp_path: Path) -> None:
        mesh = parse_inp_mesh(write(tmp_path, SIMPLE_MESH))
        assert select_nodes_on_face(mesh, "zmin", tolerance=20.0) == [1, 2, 3, 4, 5]


class TestElementTopology:
    def test_quadratic_tet_reports_four_corners(self) -> None:
        element = Element(1, "C3D10", tuple(range(1, 11)))
        assert element.corner_nodes == (1, 2, 3, 4)
        assert element.family == "tet"
        assert element.is_solid

    def test_shell_element_is_not_solid(self) -> None:
        assert not Element(1, "S3", (1, 2, 3)).is_solid

    def test_unknown_element_type_is_not_solid(self) -> None:
        assert not Element(1, "MADEUP", (1, 2)).is_solid

    def test_solid_elements_filters_shells(self, tmp_path: Path) -> None:
        content = SIMPLE_MESH + "*ELEMENT, TYPE=S3, ELSET=Skin\n3, 1, 2, 3\n"
        mesh = parse_inp_mesh(write(tmp_path, content))
        assert mesh.element_count == 3
        assert [e.eid for e in mesh.solid_elements] == [1, 2]
