"""ROS 2 launch file generation for an exported URDF (MET-706 session, 4th
and final slice of robotics-simulation-file support after MET-711/712/713).

MetaForge already produces exactly what a ROS `robot_description` parameter
needs -- ``export_urdf``'s plain, flat URDF (no xacro macros to expand).
What's missing is the standard launch wiring: a ``robot_state_publisher``
node loading that URDF, plus (optionally) ``joint_state_publisher`` and
``rviz2`` for visualization -- the same three-node pattern ROS's own
canonical example ships.

Grounded directly against the primary source: ``ros/urdf_launch``'s real
``description.launch.py``/``display.launch.py`` (fetched via `gh api` while
building this, not guessed), which establishes the exact API surface used
here -- ``LaunchDescription``, ``DeclareLaunchArgument``, ``Command``,
``LaunchConfiguration``, ``Node``, ``IfCondition``/``UnlessCondition``. This
generator combines both of those files' behavior into one standalone
launch file (rather than depending on the separately-installed
``urdf_launch`` package via ``IncludeLaunchDescription``, since MetaForge's
output should be portable on its own, not assume that package is present).

This emits Python *source text* -- like the URDF/SDF/USD generators, no
``launch``/``launch_ros`` import is needed to build it (this module never
runs as a real launch file itself, it only writes one).
"""

from __future__ import annotations


def build_ros2_launch_py(
    *,
    robot_name: str,
    default_urdf_path: str,
    include_joint_state_publisher_gui: bool = True,
    include_rviz: bool = True,
) -> str:
    """Build a standalone ROS 2 launch file for ``robot_name``.

    ``default_urdf_path`` is the launch argument's default value, not a
    baked-in path -- overridable at invocation time via
    ``ros2 launch <file> urdf_path:=/other/path.urdf``, matching how
    ``urdf_launch``'s own ``description.launch.py`` parametrizes its
    package/path arguments rather than hardcoding them.

    The URDF content is read via ``Command(['cat', ...])`` (resolved at
    launch time by the substitution system, not at Python-import time),
    the same pattern ``description.launch.py`` uses with ``xacro`` --
    MetaForge's export has no macros to expand, so ``cat`` is the direct
    equivalent for a plain URDF file.
    """
    lines = [
        '"""ROS 2 launch file, generated by MetaForge (cadquery.export_urdf '
        + "+ ros_launch.py -- MET-706).",
        "",
        f"Starts robot_state_publisher for '{robot_name}'",
    ]
    if include_joint_state_publisher_gui:
        lines.append("(with a joint_state_publisher/joint_state_publisher_gui toggle)")
    if include_rviz:
        lines.append("plus rviz2 for visualization.")
    lines.append('"""')
    header = "\n".join(lines)

    imports = [
        "from launch import LaunchDescription",
        "from launch.actions import DeclareLaunchArgument",
        "from launch.substitutions import Command, LaunchConfiguration",
        "",
        "from launch_ros.actions import Node",
        "from launch_ros.parameter_descriptions import ParameterValue",
    ]
    if include_joint_state_publisher_gui:
        imports.insert(3, "from launch.conditions import IfCondition, UnlessCondition")

    body = [
        "",
        "",
        "def generate_launch_description():",
        "    ld = LaunchDescription()",
        "",
        "    ld.add_action(DeclareLaunchArgument(",
        "        'urdf_path',",
        f"        default_value={default_urdf_path!r},",
        "        description='Absolute path to the robot URDF file',",
        "    ))",
        "",
        "    robot_description_content = ParameterValue(",
        "        Command(['cat ', LaunchConfiguration('urdf_path')]),",
        "        value_type=str,",
        "    )",
        "",
        "    ld.add_action(Node(",
        "        package='robot_state_publisher',",
        "        executable='robot_state_publisher',",
        "        parameters=[{'robot_description': robot_description_content}],",
        "    ))",
    ]

    if include_joint_state_publisher_gui:
        body += [
            "",
            "    ld.add_action(DeclareLaunchArgument(",
            "        name='jsp_gui', default_value='true', choices=['true', 'false'],",
            "        description='Flag to enable joint_state_publisher_gui',",
            "    ))",
            "    ld.add_action(Node(",
            "        package='joint_state_publisher',",
            "        executable='joint_state_publisher',",
            "        condition=UnlessCondition(LaunchConfiguration('jsp_gui')),",
            "    ))",
            "    ld.add_action(Node(",
            "        package='joint_state_publisher_gui',",
            "        executable='joint_state_publisher_gui',",
            "        condition=IfCondition(LaunchConfiguration('jsp_gui')),",
            "    ))",
        ]
    else:
        body += [
            "",
            "    ld.add_action(Node(",
            "        package='joint_state_publisher',",
            "        executable='joint_state_publisher',",
            "    ))",
        ]

    if include_rviz:
        body += [
            "",
            "    ld.add_action(Node(",
            "        package='rviz2',",
            "        executable='rviz2',",
            "        output='screen',",
            "    ))",
        ]

    body += ["", "    return ld", ""]

    return header + "\n\n" + "\n".join(imports) + "\n".join(body)
